config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'admin_setup/cost_setup'
  get 'admin_setup/department_setup'
  get 'admin_setup/transport_setup'
  get 'admin_setup/report_builder'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :inventories
  resources :file_informations
  resources :supplier_setups
  resources :transport_setups
  resources :cost_setups
  resources :order_confirmations
  resources :inventory_details
  resources :business_classifications
  resources :business_types
  resources :bankings
  resources :company_setups
  resources :departments

  devise_for :users
  resources :shipments
  resources :orders
  resources :customs_service_departments
  resources :simba_systems
  resources :insurances
  resources :kentrades
  resources :ppbs
  resources :proforma_invoices
  resources :bill_of_ladings
  resources :calculations
  resources :users
  resources :ppbs
  end

app/models/banking.rb
class Banking < ActiveRecord::Base
end

app/models/business_type.rb
class BusinessType < ActiveRecord::Base
end

app/models/company_setup.rb
class CompanySetup < ActiveRecord::Base
end

app/models/cost_setup.rb
class CostSetup < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :users
end

app/models/file_information.rb
class FileInformation < ActiveRecord::Base
	has_many :orders
	has_many :shipments, :through => :orders

	validates :file_number,:idf_date, presence: true

	accepts_nested_attributes_for :orders,
           :reject_if => :all_blank,
           :allow_destroy => true 
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
	has_many :order_confirmations
end

app/models/kentrade.rb
class Kentrade < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :shipment
    belongs_to :file_information
    belongs_to :order_confirmation

	validates :product,:lots,:quantity,:price,:rate,presence: true
	
end

app/models/ppb.rb
class Ppb < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
	    has_many :orders
	    has_many :file_informations, :through => :orders
	    
	    validates :country_of_origin,
	        :supplier,:supply_nature,:custom_entry_nos,
	        :custom_exchange_rate,
	        :custom_value, :agent_inv_nos,
	        :Quantity, :total_cost_usd, presence: true

	    accepts_nested_attributes_for :orders,
           :reject_if => :all_blank,
           :allow_destroy => true 
end

app/models/simba_system.rb
class SimbaSystem < ActiveRecord::Base
end

app/models/supplier_setup.rb
class SupplierSetup < ActiveRecord::Base
end

app/models/transport_setup.rb
class TransportSetup < ActiveRecord::Base
	has_many :order_confirmations
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :department
	has_attached_file :avatar, styles: { large: "450x450#", medium: "300x300>", thumb: "100x100#", mini: "50x50#" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  	#enums for roles
	enum role: [:user, :agent, :admin]
	after_initialize :set_default_role, :if => :new_record?

	def set_default_role
		self.role ||= :user
	end

	#def admin?
	#	self.role.include?(:admin)
	#end

	belongs_to :department
  	
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  	attr_accessor :login

  	def self.find_first_by_auth_conditions(warden_conditions)
  		conditions = warden_conditions.dup
	  	if login = conditions.delete(:login)
	    	where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  	else
	    	if conditions[:username].nil?
	      		where(conditions).first
	    	else
	      		where(username: conditions[:username]).first
	    	end
	  	end
  	end

end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_insurance, only: [:show, :edit, :update, :destroy]

  # GET /insurances
  # GET /insurances.json
  def index
    @insurances = Insurance.all.paginate(page: params[:page], per_page: 15)
  end

  # GET /insurances/1
  # GET /insurances/1.json
  def show
  end

  # GET /insurances/new
  def new
    @insurance = Insurance.new
  end

  # GET /insurances/1/edit
  def edit
  end

  # POST /insurances
  # POST /insurances.json
  def create
    @insurance = Insurance.new(insurance_params)

    respond_to do |format|
      if @insurance.save
        format.html { redirect_to @insurance, notice: 'Insurance was successfully created.' }
        format.json { render :show, status: :created, location: @insurance }
      else
        format.html { render :new }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurances/1
  # PATCH/PUT /insurances/1.json
  def update
    respond_to do |format|
      if @insurance.update(insurance_params)
        format.html { redirect_to @insurance, notice: 'Insurance was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurance }
      else
        format.html { render :edit }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurances/1
  # DELETE /insurances/1.json
  def destroy
    @insurance.destroy
    respond_to do |format|
      format.html { redirect_to insurances_url, notice: 'Insurance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurance
      @insurance = Insurance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insurance_params
      params.require(:insurance).permit(:insurance_name, :total_insurance_charges, :avatar)
    end
end

app/helpers/bankings_helper.rb
module BankingsHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ppbs_helper.rb
module PpbsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/insurances/_form.html.erb
<%= form_for(@insurance) do |f| %>
  <% if @insurance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insurance.errors.count, "error") %> prohibited this insurance from being saved:</h2>

      <ul>
      <% @insurance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="exampleInputFile">Insurance Name</label>
    <%= f.text_field :insurance_name, :step => 'any', class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="exampleInputFile">Total Insure Charges</label>
    <%= f.text_field :total_insurance_charges, :step => 'any', class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="exampleInputFile">Attachments</label>
    <%#= f.file_field :avatar %>
    <%= f.file_field :avatar, :step => 'any' %>
  </div>

  <!--<div class="form-group">
    <label for="exampleInputFile">Attachments</label>
    <%= f.file_field :avatar, :step => 'any', class: 'form-control' %>
  </div>-->

  <div class="box-footer">
    <%= f.submit "Submit", class: "btn btn-success btn-sm" %>
      <!--<button type="submit" class="btn btn-primary">Submit</button>-->
  </div>
    <%#= link_to 'Next Form', shipments_path %>
<% end %>

app/views/insurances/edit.html.erb
<div class="box box-primary col-lg-6">
  <div class="box-header with-border ">
    <h3 class="box-title">Editing Insurance </h3>
    <%= link_to 'Cancel', insurances_path, class: "pull-right btn btn-info btn-sm" %>
  </div>
  <div class="box-body">
	<%= render 'form' %>
	<!--<%= link_to 'Show', @insurance %> |
	<%= link_to 'Back', insurances_path %>-->
  </div>
</div>
			

app/views/insurances/index.html.erb
<% @title="Insurances" %>
<p id="notice"><%= notice %></p>
<div class="col-md-12">
  <div class="box">
    <div class="box-header with-border">
      <h1 class="box-title">Insurance Listings</h1>    
        <h3 class="box-title pull-right ">
          <%= link_to 'Add Insurance', new_insurance_path, class: "btn btn-warning btn-sm" %>
        </h3>
    </div>
    <div class="box-body">
      <table class="table table-bordered table-hover">
          <tr>
            <th>Insurance name</th>
            <th>Total insurance charges</th>
            <th colspan="2"></th>
          <tr>
          <% @insurances.each do |insurance| %>
            <tr>
              <td><%= insurance.insurance_name %></td>
              <td><%= insurance.total_insurance_charges %></td>
              <td><%= link_to 'Show', insurance %></td>
              <td><%= link_to 'Delete', insurance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tr>
      </table>
    </div>
    <div class="box-footer clearfix">
      <ul class="pagination pagination-sm no-margin pull-right">
        <li><%= will_paginate @insurances, renderer: BootstrapPagination::Rails %></li>
      </ul>
    </div>
  </div><!-- /.box -->
</div><!-- /.col -->

app/views/insurances/new.html.erb
<div class="box box-primary col-lg-6">
  <div class="box-header with-border ">
    <h3 class="box-title">New Insurance </h3>
    <%= link_to 'Cancel', insurances_path, class: "pull-right btn btn-info btn-sm" %>
  </div>
  <div class="box-body">
	<%= render 'form' %>
  </div>
</div>
			

app/views/insurances/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Insurance name:</strong>
  <%= image_tag @insurance.avatar.url(:medium) %>
</p>

<p>
  <strong>Insurance name:</strong>
  <%= @insurance.insurance_name %>
</p>

<p>
  <strong>Total insurance charges:</strong>
  <%= @insurance.total_insurance_charges %>
</p>

<%= link_to 'Edit', edit_insurance_path(@insurance) %> |
<%= link_to 'Back', insurances_path %>