config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'admin_setup/cost_setup'
  get 'admin_setup/department_setup'
  get 'admin_setup/transport_setup'
  get 'admin_setup/report_builder'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :inventories
  resources :file_informations
  resources :supplier_setups
  resources :transport_setups
  resources :cost_setups
  resources :order_confirmations
  resources :inventory_details
  resources :business_classifications
  resources :business_types
  resources :bankings
  resources :company_setups
  resources :departments

  devise_for :users
  resources :shipments
  resources :orders
  resources :customs_service_departments
  resources :simba_systems
  resources :insurances
  resources :kentrades
  resources :ppbs
  resources :proforma_invoices
  resources :bill_of_ladings
  resources :calculations
  resources :users
  resources :ppbs
  end

app/models/banking.rb
class Banking < ActiveRecord::Base
end

app/models/business_type.rb
class BusinessType < ActiveRecord::Base
end

app/models/company_setup.rb
class CompanySetup < ActiveRecord::Base
end

app/models/cost_setup.rb
class CostSetup < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :users
end

app/models/file_information.rb
class FileInformation < ActiveRecord::Base
	has_many :orders
	has_many :shipments, :through => :orders

	validates :file_number,:idf_date, presence: true

	accepts_nested_attributes_for :orders,
           :reject_if => :all_blank,
           :allow_destroy => true 
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
	has_many :order_confirmations
end

app/models/kentrade.rb
class Kentrade < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :shipment
    belongs_to :file_information
    belongs_to :order_confirmation

	validates :product,:lots,:quantity,:price,:rate,presence: true
	
end

app/models/ppb.rb
class Ppb < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
	    has_many :orders
	    has_many :file_informations, :through => :orders
	    
	    validates :country_of_origin,
	        :supplier,:supply_nature,:custom_entry_nos,
	        :custom_exchange_rate,
	        :custom_value, :agent_inv_nos,
	        :Quantity, :total_cost_usd, presence: true

	    accepts_nested_attributes_for :orders,
           :reject_if => :all_blank,
           :allow_destroy => true 
end

app/models/simba_system.rb
class SimbaSystem < ActiveRecord::Base
end

app/models/supplier_setup.rb
class SupplierSetup < ActiveRecord::Base
end

app/models/transport_setup.rb
class TransportSetup < ActiveRecord::Base
	has_many :order_confirmations
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :department
	has_attached_file :avatar, styles: { large: "450x450#", medium: "300x300>", thumb: "100x100#", mini: "50x50#" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  	#enums for roles
	enum role: [:user, :agent, :admin]
	after_initialize :set_default_role, :if => :new_record?

	def set_default_role
		self.role ||= :user
	end

	#def admin?
	#	self.role.include?(:admin)
	#end

	belongs_to :department
  	
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  	attr_accessor :login

  	def self.find_first_by_auth_conditions(warden_conditions)
  		conditions = warden_conditions.dup
	  	if login = conditions.delete(:login)
	    	where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  	else
	    	if conditions[:username].nil?
	      		where(conditions).first
	    	else
	      		where(username: conditions[:username]).first
	    	end
	  	end
  	end

end

app/controllers/cost_setups_controller.rb
class CostSetupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cost_setup, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized

  # GET /cost_setups
  # GET /cost_setups.json
  def index
    @cost_setups = CostSetup.all.paginate(page: params[:page], per_page: 15)
    authorize User
  end

  # GET /cost_setups/1
  # GET /cost_setups/1.json
  def show
    #@cost_setup = CostSetup.find(params[:id])
    authorize User
  end

  # GET /cost_setups/new
  def new
    @cost_setup = CostSetup.new
    authorize User
  end

  # GET /cost_setups/1/edit
  def edit
    authorize User
  end

  # POST /cost_setups
  # POST /cost_setups.json
  def create
    @cost_setup = CostSetup.new(cost_setup_params)
    authorize User

    respond_to do |format|
      if @cost_setup.save
        format.html { redirect_to @cost_setup, notice: 'Cost setup was successfully created.' }
        format.json { render :show, status: :created, location: @cost_setup }
      else
        format.html { render :new }
        format.json { render json: @cost_setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cost_setups/1
  # PATCH/PUT /cost_setups/1.json
  def update
    respond_to do |format|
      if @cost_setup.update(cost_setup_params)
        format.html { redirect_to @cost_setup, notice: 'Cost setup was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost_setup }
      else
        format.html { render :edit }
        format.json { render json: @cost_setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cost_setups/1
  # DELETE /cost_setups/1.json
  def destroy
    @cost_setup.destroy
    authorize User
    respond_to do |format|
      format.html { redirect_to cost_setups_url, notice: 'Cost setup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost_setup
      @cost_setup = CostSetup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_setup_params
      params.require(:cost_setup).permit(:cost_code, :cost_type, :cost_type_setup, :currency, :currency_rate)
    end
end

app/helpers/bankings_helper.rb
module BankingsHelper
end

app/helpers/cost_setups_helper.rb
module CostSetupsHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ppbs_helper.rb
module PpbsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cost_setups/_form.html.erb
<%= form_for(@cost_setup) do |f| %>
  <% if @cost_setup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost_setup.errors.count, "error") %> prohibited this cost_setup from being saved:</h2>

      <ul>
      <% @cost_setup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="exampleInputEmail1">Cost Code</label>
    <%= f.text_area :cost_code, :step => 'any', class: 'form-control' %>
  </div>

  <div class="form-group">
    <label for="exampleInputEmail1">Cost Type</label>
    <%= f.text_field :cost_type, :step => 'any', class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Cost Type Setup</label>
    <%= f.text_field :cost_type_setup, :step => 'any', class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Currency</label>
    <%= f.text_field :currency, :step => 'any', class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Currency Rate</label>
    <%= f.text_field :currency_rate, :step => 'any', class: 'form-control' %>
  </div>
 <div class="box-footer">
    <%= f.submit "Submit", class: "btn btn-success btn-sm" %>
      <!--<button type="submit" class="btn btn-primary">Submit</button>-->
  </div> 
<% end %>

app/views/cost_setups/edit.html.erb
<div class="box box-primary col-lg-6">
  <div class="box-header with-border ">
    <h3 class="box-title">Edit Cost Setup</h3>
	<%= link_to 'Cancel', cost_setups_path, class: "pull-right btn btn-info btn-sm" %>
  </div>
  <div class="box-body">
	<%= render 'form' %>
  </div>
</div>

app/views/cost_setups/index.html.erb
<% @title="Cost Setups" %>
<p id="notice"><%= notice %></p>

<div class="col-md-12">
  <div class="box">
    <div class="box-header with-border">
      <h1 class="box-title">Cost Setup Listings</h1>
    
      <h3 class="box-title pull-right ">
        <%= link_to "New Cost Setup", new_cost_setup_path, class: "btn btn-warning btn-sm" %>
      </h3>
    </div>
    <div class="box-body">
      <table class="table table-bordered table-hover">
        <tr>
          <th>Cost code</th>
          <th>Cost type</th>
          <th>Cost type setup</th>
          <th>Currency</th>
          <th>Currency rate</th>
          <th colspan="2"></th>
        </tr>
        <% @cost_setups.each do |cost_setup| %>
          <tr>
            <td><%= cost_setup.cost_code %></td>
            <td><%= cost_setup.cost_type %></td>
            <td><%= cost_setup.cost_type_setup %></td>
            <td><%= cost_setup.currency %></td>
            <td><%= cost_setup.currency_rate %></td>
            <td><%= link_to 'View', cost_setup %></td>
            <td><%= link_to 'Delete', cost_setup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </table>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
      <ul class="pagination pagination-sm no-margin pull-right">
        <li><%= will_paginate @cost_setups, renderer: BootstrapPagination::Rails %></li>
      </ul>
    </div>
  </div><!-- /.box -->
</div><!-- /.col -->

app/views/cost_setups/new.html.erb
<div class="box box-primary col-lg-6">
  <div class="box-header with-border ">
    <h3 class="box-title">New Cost Setup</h3>
	<%= link_to 'Cancel', cost_setups_path, class: "pull-right btn btn-info btn-sm" %>
  </div>
  <div class="box-body">
	<%= render 'form' %>
  </div>
</div>

app/views/cost_setups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cost code:</strong>
  <%= @cost_setup.cost_code %>
</p>

<p>
  <strong>Cost type:</strong>
  <%= @cost_setup.cost_type %>
</p>

<p>
  <strong>Cost type setup:</strong>
  <%= @cost_setup.cost_type_setup %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @cost_setup.currency %>
</p>

<p>
  <strong>Currency rate:</strong>
  <%= @cost_setup.currency_rate %>
</p>

<%= link_to 'Edit', edit_cost_setup_path(@cost_setup) %> |
<%= link_to 'Back', cost_setups_path %>