config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'admin_setup/cost_setup'
  get 'admin_setup/department_setup'
  get 'admin_setup/transport_setup'
  get 'admin_setup/report_builder'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :inventories
  resources :file_informations
  resources :supplier_setups
  resources :transport_setups
  resources :cost_setups
  resources :order_confirmations
  resources :inventory_details
  resources :business_classifications
  resources :business_types
  resources :bankings
  resources :company_setups
  resources :departments

  devise_for :users
  resources :shipments
  resources :orders
  resources :customs_service_departments
  resources :simba_systems
  resources :insurances
  resources :kentrades
  resources :ppbs
  resources :proforma_invoices
  resources :bill_of_ladings
  resources :calculations
  resources :users
  resources :ppbs
  end

app/models/banking.rb
class Banking < ActiveRecord::Base
end

app/models/business_type.rb
class BusinessType < ActiveRecord::Base
end

app/models/company_setup.rb
class CompanySetup < ActiveRecord::Base
end

app/models/cost_setup.rb
class CostSetup < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :users
end

app/models/file_information.rb
class FileInformation < ActiveRecord::Base
	has_many :orders
	has_many :shipments, :through => :orders

	validates :file_number,:idf_date, presence: true

	accepts_nested_attributes_for :orders,
           :reject_if => :all_blank,
           :allow_destroy => true 
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
	has_many :order_confirmations
end

app/models/inventory_detail.rb
class InventoryDetail < ActiveRecord::Base
end

app/models/kentrade.rb
class Kentrade < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :shipment
    belongs_to :file_information
    belongs_to :order_confirmation

	validates :product,:lots,:quantity,:price,:rate,presence: true
	
end

app/models/ppb.rb
class Ppb < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
	    has_many :orders
	    has_many :file_informations, :through => :orders
	    
	    validates :country_of_origin,
	        :supplier,:supply_nature,:custom_entry_nos,
	        :custom_exchange_rate,
	        :custom_value, :agent_inv_nos,
	        :Quantity, :total_cost_usd, presence: true

	    accepts_nested_attributes_for :orders,
           :reject_if => :all_blank,
           :allow_destroy => true 
end

app/models/simba_system.rb
class SimbaSystem < ActiveRecord::Base
end

app/models/supplier_setup.rb
class SupplierSetup < ActiveRecord::Base
end

app/models/transport_setup.rb
class TransportSetup < ActiveRecord::Base
	has_many :order_confirmations
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :department
	has_attached_file :avatar, styles: { large: "450x450#", medium: "300x300>", thumb: "100x100#", mini: "50x50#" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  	#enums for roles
	enum role: [:user, :agent, :admin]
	after_initialize :set_default_role, :if => :new_record?

	def set_default_role
		self.role ||= :user
	end

	#def admin?
	#	self.role.include?(:admin)
	#end

	belongs_to :department
  	
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  	attr_accessor :login

  	def self.find_first_by_auth_conditions(warden_conditions)
  		conditions = warden_conditions.dup
	  	if login = conditions.delete(:login)
	    	where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  	else
	    	if conditions[:username].nil?
	      		where(conditions).first
	    	else
	      		where(username: conditions[:username]).first
	    	end
	  	end
  	end

end

app/controllers/ppbs_controller.rb
class PpbsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ppb, only: [:show, :edit, :update, :destroy]

  # GET /ppbs
  # GET /ppbs.json
  def index
    @ppbs = Ppb.all.paginate(page: params[:page], per_page: 15)
  end

  # GET /ppbs/1
  # GET /ppbs/1.json
  def show
  end

  # GET /ppbs/new
  def new
    @ppb = Ppb.new
  end

  # GET /ppbs/1/edit
  def edit
  end

  # POST /ppbs
  # POST /ppbs.json
  def create
    @ppb = Ppb.new(ppb_params)

    respond_to do |format|
      if @ppb.save
        format.html { redirect_to @ppb, notice: 'Pharmaceutical Listing was successfully created.' }
        format.json { render :show, status: :created, location: @ppb }
      else
        format.html { render :new }
        format.json { render json: @ppb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ppbs/1
  # PATCH/PUT /ppbs/1.json
  def update
    respond_to do |format|
      if @ppb.update(ppb_params)
        format.html { redirect_to @ppb, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @ppb }
      else
        format.html { render :edit }
        format.json { render json: @ppb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ppbs/1
  # DELETE /ppbs/1.json
  def destroy
    @ppb.destroy
    respond_to do |format|
      format.html { redirect_to ppbs_url, notice: 'Listing was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ppb
      @ppb = Ppb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ppb_params
      params.require(:ppb).permit(:avatar,:UCR_Number, :application_date)
    end
end

app/helpers/bankings_helper.rb
module BankingsHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ppbs_helper.rb
module PpbsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ppbs/_form.html.erb
<%= form_for @ppb, url: ppbs_path, html: {multipart: true} do |f| %>
  <% if @ppb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ppb.errors.count, "error") %> prohibited this ppb from being saved:</h2>

      <ul>
      <% @ppb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="exampleInputFile">Upload Image</label>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-group">
    <label for="exampleInputFile">UCR Number</label>
    <%= f.text_field :UCR_Number, :step => 'any', class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Application Date:</label>
    <div class="input-group">
      <div class="input-group-addon">
        <i class="fa fa-calendar"></i>
      </div>
      <%= f.date_select :application_date, :step => 'any', class: 'form-control' %>
      <!--<input class="form-control" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="" type="text">-->
    </div><!-- /.input group -->
  </div>

  <!--<div class="form-group">
    <label for="exampleInputFile">Application Date</label>
    <%= f.date_select :application_date, :step => 'any', class: 'form-control' %>
  </div>-->

  <div class="box-footer">
    <%= f.submit "Submit", class: "btn btn-success btn-sm" %>
      <!--<button type="submit" class="btn btn-primary">Submit</button>-->
  </div>


    
  <!--<div class="actions">
  </div>-->
<% end %>

app/views/ppbs/edit.html.erb
<div class="box box-primary col-lg-6">
  <div class="box-header with-border ">
    <h3 class="box-title">Edit Pharmacy Board</h3>
    <%= link_to 'Cancel', ppbs_path, class: "pull-right btn btn-info btn-sm" %>
  </div>
  <div class="box-body">
	<%= render 'form' %>
		<!--<%#= link_to 'Show', @ppb %> |
		<%#= link_to 'Back', ppbs_path %>-->
  </div>
</div>
			

app/views/ppbs/index.html.erb
<% @title="PPBS" %>
<p id="notice"><%= notice %></p>

<div class="col-md-12">
  <div class="box">
    <div class="box-header with-border">
      <h1 class="box-title">Pharmaceutical Listings</h1>    
        <h3 class="box-title pull-right ">
          <%= link_to 'Create Pharmacy', new_ppb_path, class: "btn btn-warning btn-sm" %>
        </h3>
    </div>
    <div class="box-body">
      <table class="table table-bordered table-hover">
          <tr>
            <th>Ucr number</th>
            <th>Application date</th>
            <th colspan="2"></th>
          </tr>
          <tr>
          <% @ppbs.each do |ppb| %>
          <tr>
            <td><%= ppb.UCR_Number %></td>
            <td><%= ppb.application_date %></td>
            <td><%= link_to 'Show', ppb %></td>
            <td><%= link_to 'Delete', ppb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tr>
      </table>
    </div>
    <div class="box-footer clearfix">
      <ul class="pagination pagination-sm no-margin pull-right">
        <li><%= will_paginate @ppbs, renderer: BootstrapPagination::Rails %></li>
      </ul>
    </div>
  </div><!-- /.box -->
</div><!-- /.col -->


              
        

app/views/ppbs/new.html.erb
<div class="box box-primary col-lg-6">
  <div class="box-header with-border ">
    <h3 class="box-title">Add Pharmacy Board</h3>
	<%= link_to 'Cancel', ppbs_path, class: "pull-right btn btn-info btn-sm" %>
  </div>
  <div class="box-body">
	<%= render 'form' %>
  </div>
</div>					

app/views/ppbs/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @ppb.avatar.url(:medium) %>
</p>
<p>
  <strong>Ucr number:</strong>
  <%= @ppb.UCR_Number %>
</p>

<p>
  <strong>Application date:</strong>
  <%= @ppb.application_date %>
</p>

<%= link_to 'Edit', edit_ppb_path(@ppb) %> |
<%= link_to 'Back', ppbs_path %>