config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'admin_setup/cost_setup'
  get 'admin_setup/department_setup'
  get 'admin_setup/transport_setup'
  get 'admin_setup/report_builder'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :inventories
  resources :file_informations
  resources :supplier_setups
  resources :transport_setups
  resources :cost_setups
  resources :order_confirmations
  resources :inventory_details
  resources :business_classifications
  resources :business_types
  resources :bankings
  resources :company_setups
  resources :departments

  devise_for :users
  resources :shipments
  resources :orders
  resources :customs_service_departments
  resources :simba_systems
  resources :insurances
  resources :kentrades
  resources :ppbs
  resources :proforma_invoices
  resources :bill_of_ladings
  resources :calculations
  resources :users
  resources :ppbs
  end

app/models/banking.rb
class Banking < ActiveRecord::Base
end

app/models/business_type.rb
class BusinessType < ActiveRecord::Base
end

app/models/company_setup.rb
class CompanySetup < ActiveRecord::Base
end

app/models/cost_setup.rb
class CostSetup < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :users
end

app/models/file_information.rb
class FileInformation < ActiveRecord::Base
	has_many :orders
	has_many :shipments, :through => :orders

	validates :file_number,:idf_date, presence: true

	accepts_nested_attributes_for :orders,
           :reject_if => :all_blank,
           :allow_destroy => true 
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
	has_many :order_confirmations
end

app/models/inventory_detail.rb
class InventoryDetail < ActiveRecord::Base
end

app/models/kentrade.rb
class Kentrade < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :shipment
    belongs_to :file_information
    belongs_to :order_confirmation

	validates :product,:lots,:quantity,:price,:rate,presence: true
	
end

app/models/ppb.rb
class Ppb < ActiveRecord::Base
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
	    has_many :orders
	    has_many :file_informations, :through => :orders
	    
	    validates :country_of_origin,
	        :supplier,:supply_nature,:custom_entry_nos,
	        :custom_exchange_rate,
	        :custom_value, :agent_inv_nos,
	        :Quantity, :total_cost_usd, presence: true

	    accepts_nested_attributes_for :orders,
           :reject_if => :all_blank,
           :allow_destroy => true 
end

app/models/simba_system.rb
class SimbaSystem < ActiveRecord::Base
end

app/models/supplier_setup.rb
class SupplierSetup < ActiveRecord::Base
end

app/models/transport_setup.rb
class TransportSetup < ActiveRecord::Base
	has_many :order_confirmations
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :department
	has_attached_file :avatar, styles: { large: "450x450#", medium: "300x300>", thumb: "100x100#", mini: "50x50#" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  	#enums for roles
	enum role: [:user, :agent, :admin]
	after_initialize :set_default_role, :if => :new_record?

	def set_default_role
		self.role ||= :user
	end

	#def admin?
	#	self.role.include?(:admin)
	#end

	belongs_to :department
  	
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  	attr_accessor :login

  	def self.find_first_by_auth_conditions(warden_conditions)
  		conditions = warden_conditions.dup
	  	if login = conditions.delete(:login)
	    	where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  	else
	    	if conditions[:username].nil?
	      		where(conditions).first
	    	else
	      		where(username: conditions[:username]).first
	    	end
	  	end
  	end

end

app/controllers/bankings_controller.rb
class BankingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_banking, only: [:show, :edit, :update, :destroy]

  # GET /bankings
  # GET /bankings.json
  def index
    @bankings = Banking.all.paginate(page: params[:page], per_page: 15)
  end

  # GET /bankings/1
  # GET /bankings/1.json
  def show
  end

  # GET /bankings/new
  def new
    @banking = Banking.new
  end

  # GET /bankings/1/edit
  def edit
  end

  # POST /bankings
  # POST /bankings.json
  def create
    @banking = Banking.new(banking_params)

    respond_to do |format|
      if @banking.save
        format.html { redirect_to @banking, notice: 'Banking was successfully created.' }
        format.json { render :show, status: :created, location: @banking }
      else
        format.html { render :new }
        format.json { render json: @banking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bankings/1
  # PATCH/PUT /bankings/1.json
  def update
    respond_to do |format|
      if @banking.update(banking_params)
        format.html { redirect_to @banking, notice: 'Banking was successfully updated.' }
        format.json { render :show, status: :ok, location: @banking }
      else
        format.html { render :edit }
        format.json { render json: @banking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bankings/1
  # DELETE /bankings/1.json
  def destroy
    @banking.destroy
    respond_to do |format|
      format.html { redirect_to bankings_url, notice: 'Banking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banking
      @banking = Banking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banking_params
      params.require(:banking).permit(:bank_name, :bank_branch, :Account_number, :branch_code, :branch_description, :swift_code, :other_details, :email)
    end
end

app/helpers/bankings_helper.rb
module BankingsHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ppbs_helper.rb
module PpbsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bankings/_form.html.erb
<%= form_for(@banking) do |f| %>
  <% if @banking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banking.errors.count, "error") %> prohibited this banking from being saved:</h2>

      <ul>
      <% @banking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="exampleInputEmail1">Bank Name</label>
    <%= f.text_field :bank_name, :step => 'any', class: 'form-control' %>
  </div>
   <div class="form-group">
    <label for="exampleInputEmail1">Bank Branch</label>
    <%= f.text_field :bank_branch, :step => 'any', class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Account Number</label>
    <%= f.number_field :Account_number, :step => 'any', class: 'form-control' %>
  </div>
   <div class="form-group">
    <label for="exampleInputEmail1">Branch Code</label>
    <%= f.number_field :branch_code, :step => 'any', class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Branch Description</label>
    <%= f.text_area :branch_description, :step => 'any', class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Swift Code</label>
    <%= f.number_field :swift_code, :step => 'any', class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Other Details</label>
    <%= f.text_area :other_details, :step => 'any', class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email</label>
    <%= f.text_area :email, :step => 'any', class: 'form-control' %>
  </div>

  <div class="box-footer">
    <%= f.submit "Submit", class: "btn btn-success btn-sm" %>
      <!--<button type="submit" class="btn btn-primary">Submit</button>-->
  </div>  

<% end %>

app/views/bankings/edit.html.erb
<div class="box box-primary col-lg-6">
  <div class="box-header with-border ">
    <h3 class="box-title">Edit Banking</h3>
	<%= link_to 'Cancel', bankings_path, class: "pull-right btn btn-info btn-sm" %>
  </div>
  <div class="box-body">
	<%= render 'form' %>
  </div>
</div>

app/views/bankings/index.html.erb
<% @title="Bankings" %>
<p id="notice"><%= notice %></p>

<div class="col-md-12">
  <div class="box">
    <div class="box-header with-border">
      <h1 class="box-title">Banking Listings</h1>
    
      <h3 class="box-title pull-right ">
        <%= link_to "New Company Setup", new_banking_path, class: "btn btn-warning btn-sm" %>
      </h3>
    </div>
    <div class="box-body">
      <table class="table table-bordered table-hover">
        <tr>
          <th>Bank name</th>
          <th>Bank branch</th>
          <th>Account number</th>
          <th>Branch code</th>
          <th>Branch description</th>
          <th>Swift code</th>
          <th>Other details</th>
          <th>Email</th>
          <th colspan="2"></th>
        </tr>
        <% @bankings.each do |banking| %>
          <tr>
            <td><%= banking.bank_name %></td>
            <td><%= banking.bank_branch %></td>
            <td><%= banking.Account_number %></td>
            <td><%= banking.branch_code %></td>
            <td><%= banking.branch_description %></td>
            <td><%= banking.swift_code %></td>
            <td><%= banking.other_details %></td>
            <td><%= banking.email %></td>
            <td><%= link_to 'Show', banking %></td>
            <td><%= link_to 'Delete', banking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </table>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
      <ul class="pagination pagination-sm no-margin pull-right">
        <li><%= will_paginate @bankings, renderer: BootstrapPagination::Rails %></li>
      </ul>
    </div>
  </div><!-- /.box -->
</div><!-- /.col -->

app/views/bankings/new.html.erb
<div class="box box-primary col-lg-6">
  <div class="box-header with-border ">
    <h3 class="box-title">New Banking</h3>
	<%= link_to 'Cancel', bankings_path, class: "pull-right btn btn-info btn-sm" %>
  </div>
  <div class="box-body">
	<%= render 'form' %>
  </div>
</div>

app/views/bankings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bank name:</strong>
  <%= @banking.bank_name %>
</p>

<p>
  <strong>Bank branch:</strong>
  <%= @banking.bank_branch %>
</p>

<p>
  <strong>Account number:</strong>
  <%= @banking.Account_number %>
</p>

<p>
  <strong>Branch code:</strong>
  <%= @banking.branch_code %>
</p>

<p>
  <strong>Branch description:</strong>
  <%= @banking.branch_description %>
</p>

<p>
  <strong>Swift code:</strong>
  <%= @banking.swift_code %>
</p>

<p>
  <strong>Other details:</strong>
  <%= @banking.other_details %>
</p>

<p>
  <strong>Email:</strong>
  <%= @banking.email %>
</p>

<%= link_to 'Edit', edit_banking_path(@banking) %> |
<%= link_to 'Back', bankings_path %>